# Generated by Django 3.2.16 on 2022-12-01 09:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0007_auto_20221201_0836'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='profile',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='profiles.profile'),
        ),
    ]
