# Generated by Django 3.2.16 on 2022-12-01 09:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0008_alter_notification_profile'),
    ]

    operations = [
        migrations.RenameField(
            model_name='notification',
            old_name='profile',
            new_name='to',
        ),
    ]
