# Generated by Django 3.2.16 on 2022-12-01 13:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0012_auto_20221201_1346'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='notification',
            name='to',
        ),
    ]
