# Generated by Django 3.2.16 on 2022-12-01 13:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0013_remove_notification_to'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='to',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='profiles.profile'),
            preserve_default=False,
        ),
    ]
