# Generated by Django 3.2.16 on 2022-12-10 19:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0014_auto_20221210_1943'),
        ('profiles', '0016_alter_notification_sender'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='saved',
            field=models.ManyToManyField(blank=True, related_name='saved_by', to='recipes.Recipe'),
        ),
    ]
