# Generated by Django 3.2.16 on 2022-12-12 23:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0015_remove_recipe_saved'),
        ('profiles', '0017_profile_saved'),
    ]

    operations = [
        migrations.CreateModel(
            name='Note',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('body', models.TextField()),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notes', to='profiles.profile')),
                ('recipe', models.ManyToManyField(blank=True, related_name='notes', to='recipes.Recipe')),
            ],
        ),
    ]
