# Generated by Django 3.2.16 on 2022-12-13 08:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0015_remove_recipe_saved'),
        ('profiles', '0018_note'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='note',
            name='recipe',
        ),
        migrations.AddField(
            model_name='note',
            name='recipe',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notes', to='recipes.recipe'),
        ),
    ]
