# Generated by Django 3.2.16 on 2022-12-06 08:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tag', models.CharField(choices=[('BREAKFAST', 'Breakfast'), ('LUNCH', 'Lunch'), ('DINNER', 'Dinner'), ('DESSERT', 'Dessert'), ('QUICKANDEASY', 'Quick & Easy'), ('LOW CALORIE', 'Low Calorie'), ('HEALTHY', 'Healthy'), ('VEGETARIAN', 'Vegetarian'), ('VEGAN', 'Vegan'), ('LOWCARB', 'Low Carb'), ('GLUTENFREE', 'Gluten Free'), ('ONABUDGET', 'On a Budget'), ('MEALPREP', 'Meal Prep')], max_length=12)),
            ],
        ),
    ]
