TAGS = [
    ('Breakfast', 'Breakfast'),
    ('Lunch', 'Lunch'),
    ('Dinner', 'Dinner'),
    ('Dessert', 'Dessert'),
    ('Quick and Easy', 'Quick & Easy'),
    ('Low Calorie', 'low-calorie'),
    ('Healthy', 'Healthy'),
    ('Vegetarian', 'Vegetarian'),
    ('Vegan', 'Vegan'),
    ('Low Carb', 'Low Carb'),
    ('Gluten Free', 'Gluten Free'),
    ('On a Budget', 'On a Budget'),
    ('Prep Ahead', 'Prep Ahead'),
]
