# Generated by Django 3.2.16 on 2022-11-24 21:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='removed',
            field=models.BooleanField(default=False),
        ),
    ]
