# Generated by Django 3.2.16 on 2022-11-30 15:00

import cloudinary.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0005_auto_20221130_1353'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='image',
            field=cloudinary.models.CloudinaryField(default='placeholder', max_length=255, verbose_name='image'),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='ingredients',
            field=models.TextField(default='placeholder'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='recipe',
            name='steps',
            field=models.TextField(default='placeholder'),
            preserve_default=False,
        ),
    ]
