# Generated by Django 3.2.16 on 2022-12-01 07:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0006_auto_20221130_1500'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='private',
            field=models.BooleanField(default=False),
        ),
    ]
