# Generated by Django 3.2.16 on 2022-12-06 08:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
        ('recipes', '0010_auto_20221205_2027'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='tags',
            field=models.ManyToManyField(to='home.Tag'),
        ),
    ]
