# Generated by Django 3.2.16 on 2022-12-06 22:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0012_auto_20221206_2050'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='tags',
            field=models.CharField(blank=True, choices=[('BREAKFAST', 'Breakfast'), ('LUNCH', 'Lunch'), ('DINNER', 'Dinner'), ('DESSERT', 'Dessert'), ('QUICKANDEASY', 'Quick & Easy'), ('LOW CALORIE', 'Low Calorie'), ('HEALTHY', 'Healthy'), ('VEGETARIAN', 'Vegetarian'), ('VEGAN', 'Vegan'), ('LOWCARB', 'Low Carb'), ('GLUTENFREE', 'Gluten Free'), ('ONABUDGET', 'On a Budget'), ('MEALPREP', 'Meal Prep')], max_length=200),
        ),
    ]
