# Generated by Django 3.2.16 on 2022-12-12 23:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0014_auto_20221210_1943'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='recipe',
            name='saved',
        ),
    ]
