# Generated by Django 3.2.16 on 2022-12-18 20:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0015_remove_recipe_saved'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='created_on',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='updated_on',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
