# Generated by Django 3.2.16 on 2022-12-23 19:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0016_auto_20221218_2051'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='updated_on',
            field=models.DateTimeField(blank=True),
        ),
    ]
