# Generated by Django 3.2.16 on 2022-12-23 19:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0017_alter_recipe_updated_on'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='updated_on',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
